/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApestAssessmentRouteImport } from './routes/apest-assessment'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as InteractionRouteImport } from './routes/interaction'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MinistryCallingRouteImport } from './routes/ministry-calling'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SpiritualGiftsRouteImport } from './routes/spiritual-gifts'
import { Route as WhyWeExistRouteImport } from './routes/why-we-exist'
import { Route as ArticlesCallingRouteImport } from './routes/articles_.calling'
import { Route as ArticlesRheniusRouteImport } from './routes/articles_.rhenius'
import { Route as ArticlesScudderRouteImport } from './routes/articles_.scudder'
import { Route as ArticlesSpiritualGiftsRouteImport } from './routes/articles_.spiritual-gifts'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as EventsGalleryRouteImport } from './routes/events.gallery'
import { Route as EventsPreviousRouteImport } from './routes/events.previous'
import { Route as EventsUpcomingRouteImport } from './routes/events.upcoming'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignupSplatRouteImport } from './routes/signup.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApestAssessmentRoute = ApestAssessmentRouteImport.update({
  id: '/apest-assessment',
  path: '/apest-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionRoute = InteractionRouteImport.update({
  id: '/interaction',
  path: '/interaction',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistryCallingRoute = MinistryCallingRouteImport.update({
  id: '/ministry-calling',
  path: '/ministry-calling',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiritualGiftsRoute = SpiritualGiftsRouteImport.update({
  id: '/spiritual-gifts',
  path: '/spiritual-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyWeExistRoute = WhyWeExistRouteImport.update({
  id: '/why-we-exist',
  path: '/why-we-exist',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesCallingRoute = ArticlesCallingRouteImport.update({
  id: '/articles_/calling',
  path: '/articles/calling',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRheniusRoute = ArticlesRheniusRouteImport.update({
  id: '/articles_/rhenius',
  path: '/articles/rhenius',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesScudderRoute = ArticlesScudderRouteImport.update({
  id: '/articles_/scudder',
  path: '/articles/scudder',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSpiritualGiftsRoute = ArticlesSpiritualGiftsRouteImport.update({
  id: '/articles_/spiritual-gifts',
  path: '/articles/spiritual-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const EventsGalleryRoute = EventsGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => EventsRoute,
} as any)
const EventsPreviousRoute = EventsPreviousRouteImport.update({
  id: '/previous',
  path: '/previous',
  getParentRoute: () => EventsRoute,
} as any)
const EventsUpcomingRoute = EventsUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => EventsRoute,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LoginRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSplatRoute = SignupSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apest-assessment': typeof ApestAssessmentRoute
  '/articles': typeof ArticlesRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/interaction': typeof InteractionRoute
  '/login': typeof LoginRouteWithChildren
  '/ministry-calling': typeof MinistryCallingRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRouteWithChildren
  '/spiritual-gifts': typeof SpiritualGiftsRoute
  '/why-we-exist': typeof WhyWeExistRoute
  '/articles/calling': typeof ArticlesCallingRoute
  '/articles/rhenius': typeof ArticlesRheniusRoute
  '/articles/scudder': typeof ArticlesScudderRoute
  '/articles/spiritual-gifts': typeof ArticlesSpiritualGiftsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/events/gallery': typeof EventsGalleryRoute
  '/events/previous': typeof EventsPreviousRoute
  '/events/upcoming': typeof EventsUpcomingRoute
  '/login/$': typeof LoginSplatRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apest-assessment': typeof ApestAssessmentRoute
  '/articles': typeof ArticlesRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/interaction': typeof InteractionRoute
  '/login': typeof LoginRouteWithChildren
  '/ministry-calling': typeof MinistryCallingRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRouteWithChildren
  '/spiritual-gifts': typeof SpiritualGiftsRoute
  '/why-we-exist': typeof WhyWeExistRoute
  '/articles/calling': typeof ArticlesCallingRoute
  '/articles/rhenius': typeof ArticlesRheniusRoute
  '/articles/scudder': typeof ArticlesScudderRoute
  '/articles/spiritual-gifts': typeof ArticlesSpiritualGiftsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/events/gallery': typeof EventsGalleryRoute
  '/events/previous': typeof EventsPreviousRoute
  '/events/upcoming': typeof EventsUpcomingRoute
  '/login/$': typeof LoginSplatRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apest-assessment': typeof ApestAssessmentRoute
  '/articles': typeof ArticlesRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/interaction': typeof InteractionRoute
  '/login': typeof LoginRouteWithChildren
  '/ministry-calling': typeof MinistryCallingRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRouteWithChildren
  '/spiritual-gifts': typeof SpiritualGiftsRoute
  '/why-we-exist': typeof WhyWeExistRoute
  '/articles_/calling': typeof ArticlesCallingRoute
  '/articles_/rhenius': typeof ArticlesRheniusRoute
  '/articles_/scudder': typeof ArticlesScudderRoute
  '/articles_/spiritual-gifts': typeof ArticlesSpiritualGiftsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/events/gallery': typeof EventsGalleryRoute
  '/events/previous': typeof EventsPreviousRoute
  '/events/upcoming': typeof EventsUpcomingRoute
  '/login/$': typeof LoginSplatRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apest-assessment'
    | '/articles'
    | '/assessment'
    | '/contact'
    | '/courses'
    | '/events'
    | '/faqs'
    | '/interaction'
    | '/login'
    | '/ministry-calling'
    | '/partner'
    | '/register'
    | '/signup'
    | '/spiritual-gifts'
    | '/why-we-exist'
    | '/articles/calling'
    | '/articles/rhenius'
    | '/articles/scudder'
    | '/articles/spiritual-gifts'
    | '/courses/$slug'
    | '/events/gallery'
    | '/events/previous'
    | '/events/upcoming'
    | '/login/$'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/signup/$'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apest-assessment'
    | '/articles'
    | '/assessment'
    | '/contact'
    | '/events'
    | '/faqs'
    | '/interaction'
    | '/login'
    | '/ministry-calling'
    | '/partner'
    | '/register'
    | '/signup'
    | '/spiritual-gifts'
    | '/why-we-exist'
    | '/articles/calling'
    | '/articles/rhenius'
    | '/articles/scudder'
    | '/articles/spiritual-gifts'
    | '/courses/$slug'
    | '/events/gallery'
    | '/events/previous'
    | '/events/upcoming'
    | '/login/$'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/signup/$'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/apest-assessment'
    | '/articles'
    | '/assessment'
    | '/contact'
    | '/courses'
    | '/events'
    | '/faqs'
    | '/interaction'
    | '/login'
    | '/ministry-calling'
    | '/partner'
    | '/register'
    | '/signup'
    | '/spiritual-gifts'
    | '/why-we-exist'
    | '/articles_/calling'
    | '/articles_/rhenius'
    | '/articles_/scudder'
    | '/articles_/spiritual-gifts'
    | '/courses/$slug'
    | '/events/gallery'
    | '/events/previous'
    | '/events/upcoming'
    | '/login/$'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/signup/$'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApestAssessmentRoute: typeof ApestAssessmentRoute
  ArticlesRoute: typeof ArticlesRoute
  AssessmentRoute: typeof AssessmentRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  FaqsRoute: typeof FaqsRoute
  InteractionRoute: typeof InteractionRoute
  LoginRoute: typeof LoginRouteWithChildren
  MinistryCallingRoute: typeof MinistryCallingRoute
  PartnerRoute: typeof PartnerRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRouteWithChildren
  SpiritualGiftsRoute: typeof SpiritualGiftsRoute
  WhyWeExistRoute: typeof WhyWeExistRoute
  ArticlesCallingRoute: typeof ArticlesCallingRoute
  ArticlesRheniusRoute: typeof ArticlesRheniusRoute
  ArticlesScudderRoute: typeof ArticlesScudderRoute
  ArticlesSpiritualGiftsRoute: typeof ArticlesSpiritualGiftsRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apest-assessment': {
      id: '/apest-assessment'
      path: '/apest-assessment'
      fullPath: '/apest-assessment'
      preLoaderRoute: typeof ApestAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interaction': {
      id: '/interaction'
      path: '/interaction'
      fullPath: '/interaction'
      preLoaderRoute: typeof InteractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministry-calling': {
      id: '/ministry-calling'
      path: '/ministry-calling'
      fullPath: '/ministry-calling'
      preLoaderRoute: typeof MinistryCallingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spiritual-gifts': {
      id: '/spiritual-gifts'
      path: '/spiritual-gifts'
      fullPath: '/spiritual-gifts'
      preLoaderRoute: typeof SpiritualGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-we-exist': {
      id: '/why-we-exist'
      path: '/why-we-exist'
      fullPath: '/why-we-exist'
      preLoaderRoute: typeof WhyWeExistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/calling': {
      id: '/articles_/calling'
      path: '/articles/calling'
      fullPath: '/articles/calling'
      preLoaderRoute: typeof ArticlesCallingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/rhenius': {
      id: '/articles_/rhenius'
      path: '/articles/rhenius'
      fullPath: '/articles/rhenius'
      preLoaderRoute: typeof ArticlesRheniusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/scudder': {
      id: '/articles_/scudder'
      path: '/articles/scudder'
      fullPath: '/articles/scudder'
      preLoaderRoute: typeof ArticlesScudderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/spiritual-gifts': {
      id: '/articles_/spiritual-gifts'
      path: '/articles/spiritual-gifts'
      fullPath: '/articles/spiritual-gifts'
      preLoaderRoute: typeof ArticlesSpiritualGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/events/gallery': {
      id: '/events/gallery'
      path: '/gallery'
      fullPath: '/events/gallery'
      preLoaderRoute: typeof EventsGalleryRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/previous': {
      id: '/events/previous'
      path: '/previous'
      fullPath: '/events/previous'
      preLoaderRoute: typeof EventsPreviousRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/upcoming': {
      id: '/events/upcoming'
      path: '/upcoming'
      fullPath: '/events/upcoming'
      preLoaderRoute: typeof EventsUpcomingRouteImport
      parentRoute: typeof EventsRoute
    }
    '/login/$': {
      id: '/login/$'
      path: '/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof LoginRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/$': {
      id: '/signup/$'
      path: '/$'
      fullPath: '/signup/$'
      preLoaderRoute: typeof SignupSplatRouteImport
      parentRoute: typeof SignupRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface EventsRouteChildren {
  EventsGalleryRoute: typeof EventsGalleryRoute
  EventsPreviousRoute: typeof EventsPreviousRoute
  EventsUpcomingRoute: typeof EventsUpcomingRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsGalleryRoute: EventsGalleryRoute,
  EventsPreviousRoute: EventsPreviousRoute,
  EventsUpcomingRoute: EventsUpcomingRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface LoginRouteChildren {
  LoginSplatRoute: typeof LoginSplatRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSplatRoute: LoginSplatRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupSplatRoute: typeof SignupSplatRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSplatRoute: SignupSplatRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApestAssessmentRoute: ApestAssessmentRoute,
  ArticlesRoute: ArticlesRoute,
  AssessmentRoute: AssessmentRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  FaqsRoute: FaqsRoute,
  InteractionRoute: InteractionRoute,
  LoginRoute: LoginRouteWithChildren,
  MinistryCallingRoute: MinistryCallingRoute,
  PartnerRoute: PartnerRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRouteWithChildren,
  SpiritualGiftsRoute: SpiritualGiftsRoute,
  WhyWeExistRoute: WhyWeExistRoute,
  ArticlesCallingRoute: ArticlesCallingRoute,
  ArticlesRheniusRoute: ArticlesRheniusRoute,
  ArticlesScudderRoute: ArticlesScudderRoute,
  ArticlesSpiritualGiftsRoute: ArticlesSpiritualGiftsRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
